# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2586c48b019868d5ca98b3a6663034f3a45a7163beda890f690b2207464200f3a6d228591134bea60db759e6caf481ac8828dd3c84b9119cb30403774b595b3

test:
  secret_key_base: bcc3250146ce5b12800fed4ff4621b8c7414d74546ed50e65094de862f081094166d392c0c690638cfdeb862971c43d7449c895d3f206d826c8b743c20a38665

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
